name: Build ModShot (standalone)
on: push
jobs:
  build-windows:
    name: Build ModShot for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup msys2
          uses: msys2/setup-msys2@v2
          with:
            msystem: ${{matrix.sys}}
        - name: Install packages with pacman
          shell: msys2 {0}
          run: |
            pacman -S --noconfirm  mm-common mingw-w64-${{matrix.env}}-doxygen mingw-w64-${{matrix.env}}-graphviz \
            mingw-w64-${{matrix.env}}-libffi mingw-w64-${{matrix.env}}-openssl mingw-w64-${{matrix.env}}-ninja \
            mingw-w64-${{matrix.env}}-cmake mingw-w64-${{matrix.env}}-make mingw-w64-${{matrix.env}}-ruby \
            mingw-w64-${{matrix.env}}-freetype git autotools mingw-w64-${{matrix.env}}-toolchain \
            mingw-w64-${{matrix.env}}-gcc bison
        - name: Run setup.sh
          working-directory: ${{ github.workspace }}
          shell: msys2 {0}
          run: |
              sh setup.sh
        
        - name: Build
          working-directory: ${{ github.workspace }}/build
          shell: msys2 {0}
          run: |
              cmake .. -G "Unix Makefiles"
              make
