name: Build ModShot Windows (standalone)
on: workflow_dispatch
jobs:
  build-windows:
    name: Build ModShot for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_ver: ['3.1', '3.0', '2.7', '2.5']
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup msys2
          uses: msys2/setup-msys2@v2
          with:
            msystem: ${{matrix.sys}}
        - name: Install packages with pacman
          shell: msys2 {0}
          run: |
            pacman -S --noconfirm  mm-common autoconf automake gcc make cmake libtool
        - name: Build
          working-directory: ${{ github.workspace }}
          shell: msys2 {0}
          run: |
              bash setup.sh
              cd windows
              make RUBY_VER=${{ matrix.ruby_ver }}
              source vars.sh
              cd ..
              meson build -Dmri_version=${{ matrix.ruby_ver }} --prefix=$PWD/out/
              cd build && ninja install
        - name: Create dist folder
          run: |
            mkdir ${{ runner.temp }}\built_artifact;
            move ${{ github.workspace }}\out\* ${{ runner.temp }}\built_artifact\;
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: modshot_build_windows_${{ github.sha }}_rb-${{ matrix.ruby_ver }}-${{ matrix.sys }}
            path: ${{ runner.temp }}\built_artifact