name: Build ModShot (standalone)
on: push
jobs:
  build-windows:
    name: Build ModShot for Windows
    runs-on: windows-latest
      strategy:
    matrix:
      include:
        - { sys: mingw64, env: x86_64 }
        - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup msys2
          uses: msys2/setup-msys2@v2
          with:
            msystem: ${{matrix.sys}}
        - name: Install dependencies
          shell: msys2 {0}
            run: |
              pacman -S pactoys  --noconfirm
              pacboy -S mm-common:m doxygen:m graphviz:m libffi:m \ 
              openssl:m ninja:m cmake:m make:m ruby:m freetype:m git:m \ 
              autotools:m toolchain:m gcc:m bison:m --noconfirm
        - name: Run setup.sh
          shell: msys2 {0}
            run: |
              sh ${{ github.workspace }}/setup.sh
        
        - name: Build
          shell: msys2 {0}
            run: |
              cmake -B ${{ github.workspace }}/build -G "Unix Makefiles"
              cd ${{ github.workspace }}/build
              make
