name: build-linux-baremetal
on: push
jobs:
  build-linux:
    name: Build ModShot for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install and configure conan
        run: |
          pip3 install conan
          conan remote add eliza https://api.bintray.com/conan/eliza/conan;
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan;
          mkdir ${{ runner.temp }}/build
      - name: Cache conan dependencies
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: ${{ runner.os }}-cached-conan-modules-${{ hashFiles('conanfile.py') }}
      - name: Build dependencies using conan
        run: conan install ${{ github.workspace }} --build=missing
        working-directory: ${{ runner.temp }}/build
      - name: Build ModShot
        run: conan build ${{ github.workspace }}
        working-directory: ${{ runner.temp }}/build
      - name: Create AppDir
        run: |
          mkdir ${{ runner.temp }}/dist &&
          ${{ github.workspace }}/make-linux-appdir.sh ${{ github.workspace }} ${{ runner.temp }}/build ${{ runner.temp }}/dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: modshot_build_linux_${{ github.sha }}
          path: ${{ runner.temp }}/dist
