name: Build ModShot (standalone)
on: push
jobs:
  build-windows:
    name: Build ModShot for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup msys2
          uses: msys2/setup-msys2@v2
          with:
            msystem: ${{matrix.sys}}
            pacboy: doxygen:m graphviz:m libffi:m freetype:m \ 
              openssl:m ninja:m cmake:m make:m ruby:m git:m \ 
              autotools:m toolchain:m gcc:m bison:m
        - name: Run setup.sh
          shell: msys2 {0}
          run: |
              export WORKSPACE=${{ github.workspace }}
              export REPO_ROOT=${WORKSPACE//\//}
              cd $REPO_ROOT
              sh setup.sh
        
        - name: Build
          shell: msys2 {0}
          run: |
              cmake -B ${{ github.workspace }}/build -G "Unix Makefiles"
              cd ${{ github.workspace }}/build
              make
