name: Build ModShot (standalone)
on: push
jobs:
  build-windows:
    name: Build ModShot for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup msys2
          uses: msys2/setup-msys2@v2
          with:
            msystem: ${{matrix.sys}}
        - name: Install packages with pacman
          shell: msys2 {0}
          run: |
            pacman -S --noconfirm  mm-common autoconf automake gcc make cmake libtool
        - name: Run setup.sh
          working-directory: ${{ github.workspace }}
          shell: msys2 {0}
          run: |
              sh setup.sh
              DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
              export OLD_PC=$(pkg-config --variable pc_path pkg-config)
              export PKG_CONFIG_LIBDIR="$DIR/build/exlibs/zmqpp/src:${OLD_PC}"
        - name: Build
          working-directory: ${{ github.workspace }}
          shell: msys2 {0}
          run: |
            meson build
            cd build && ninja
        - name: Create dist folder
          run: |
            mkdir ${{ runner.temp }}\built_artifact;
            move ${{ runner.temp }}\build\* {{ runner.temp }}\buildt_artifact\;
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: modshot_build_steam_windows_${{ github.sha }}
            path: ${{ runner.temp }}\built_artifact
